MVC.UI/Areas/Admin/Controllers/SubCategoryController.cs
using DAL.Entity;
using Service.Conc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.UI.Areas.Admin.Controllers
{
    public class SubCategoryController : Controller
    {
        SubCategoryService _screp=new SubCategoryService();
        // GET: Admin/SubCategory
        public ActionResult SubCategoryList()
        {
            return View(_screp.GetList());
        }

        public ActionResult CreateSubCategory()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSubCategory(SubCategory subCategory)
        {
            _screp.Add(subCategory);
            return RedirectToAction("SubCategoryList");
        }
        public ActionResult UpdateSubCategory(int? id)
        {
            return View();
        }


        [HttpPost]
        public ActionResult UpdateSubCategory(SubCategory subCategory)
        {

            _screp.Update(subCategory);
            return RedirectToAction("SubCategoryList");
        }

        public ActionResult DeleteSubCategory(Guid id)
        {
            _screp.Delete(id);
            return RedirectToAction("SubCategoryList");
        }
    }
}

MVC.UI/Areas/Admin/Views/SubCategory/CreateSubCategory.cshtml
@model DAL.Entity.SubCategory
@{
    ViewBag.Title = "CreateSubCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="card-body">
    @using (Html.BeginForm("CreateSubCategory", "SubCategory", FormMethod.Post))
    {
        <div>
            <label>SubCategoryName</label>
            @Html.TextBoxFor(x => x.SubCategoryName, new { @class = "form-control" })

        </div>
        <br />
        <div>
            <label>Description</label>
            @Html.TextBoxFor(x => x.SubDescription, new { @class = "form-control" })

        </div>

        <br />
        <button type="submit" class="btn btn-danger">AddSubCategory</button>

    }

</div>

MVC.UI/Areas/Admin/Views/SubCategory/SubCategoryList.cshtml
@model List<DAL.Entity.SubCategory>
@{
    ViewBag.Title = "SubCategoryList";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <div class="col-md-6">
                <header class="panel-heading">
                    <button type="submit" class="btn btn-warning">Create SubCategory</button>
                </header>
            </div>
            <div class="col-md-6">
                <header class="panel-heading">
                    SubCategory Table
                </header>
            </div>
            <table class="table table-striped table-advance table-hover">
                <thead>
                    <tr>
                        <th><i class="icon-bullhorn"></i> SubCategoryName</th>
                        <th class="hidden-phone"><i class="icon-question-sign"></i> Description</th>
                        
                        <th><i class=" icon-edit"></i> Status</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var subCategory in Model)
                    {
                        <tr>

                            <td><a href="#">@subCategory.SubCategoryName</a></td>
                            <td class="hidden-phone">@subCategory.SubDescription</td>
                           
                            <td><span class="label label-info label-mini">@subCategory.Status</span></td>
                            <td>
                                <button class="btn btn-success btn-xs"><i class="icon-ok"></i></button>
                                <button class="btn btn-primary btn-xs"><i class="icon-pencil">@Html.ActionLink("Update", "UpdateSubCategory", new { id = subCategory.ID })</i></button>
                                <button class="btn btn-danger btn-xs"><i class="icon-trash "></i>@Html.ActionLink("Delete", "DeleteSubCategory", new { id = subCategory.ID })</button>
                            </td>




                        </tr>
                    }

                </tbody>
            </table>
        </section>
    </div>
</div>

MVC.UI/Areas/Admin/Views/SubCategory/UpdateSubCategory.cshtml
@model DAL.Entity.SubCategory
@{
    ViewBag.Title = "UpdateSubCategory";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card-body">
    @using (Html.BeginForm("UpdateSubCategory", "SubCategory", FormMethod.Post))
    {

        <div>
            <label>SubCategoryName</label>
            @Html.TextBoxFor(x => x.SubCategoryName, new { @class = "form-control" })

        </div>
        <br />
        <div>
            <label>Description</label>
            @Html.TextBoxFor(x => x.SubDescription, new { @class = "form-control" })

        </div>

        <br />

        <button class="btn btn-warning">Update</button>
    }

</div>