MVC.UI/Areas/Admin/Controllers/SupplierController.cs
using DAL.Entity;
using Service.Conc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.UI.Areas.Admin.Controllers
{
    public class SupplierController : Controller
    {
        SupplierService _srep=new SupplierService();
        // GET: Admin/Supplier
        public ActionResult SupplierList()
        {

            return View(_srep.GetList());
        }

        public ActionResult CreateSupplier()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateSupplier(Supplier supplier)
        {
            _srep.Add(supplier);
            return RedirectToAction("SupplierList");
        }
        public ActionResult UpdateSupplier(int? id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult UpdateSupplier(Supplier supplier)
        {

            _srep.Update(supplier);
            return RedirectToAction("SupplierList");
        }

        public ActionResult DeleteSupplier(Guid id)
        {
            _srep.Delete(id);
            return RedirectToAction("SupplierList");
        }
    }
}

MVC.UI/Areas/Admin/Views/Supplier/CreateSupplier.cshtml
@model DAL.Entity.Supplier
@{
    ViewBag.Title = "CreateSupplier";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}


<div class="card-body">
    @using (Html.BeginForm("CreateSupplier","Supplier", FormMethod.Post))
    {
        <div>
            <label>CompanyName</label>
            @Html.TextBoxFor(x => x.CompanyName, new { @class = "form-control" })

        </div>
        <br />
        <div>
            <label>Address</label>
            @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })

        </div>

        <br />
        <div>
            <label>Email</label>
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            <br />
        </div>
        <button type="submit" class="btn btn-danger">AddSupplier</button>

    }

</div>

MVC.UI/Areas/Admin/Views/Supplier/SupplierList.cshtml
@model List<DAL.Entity.Supplier>
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <section class="panel">
            <div class="col-md-6">
                <header class="panel-heading">
                    <button type="submit" class="btn btn-warning">Create Supplier</button>
                </header>
            </div>
            <div class="col-md-6">
                <header class="panel-heading">
                    Supplier Table
                </header>
            </div>
            <table class="table table-striped table-advance table-hover">
                <thead>
                    <tr>
                        <th><i class="icon-bullhorn"></i> CompanyName</th>
                        <th class="hidden-phone"><i class="icon-question-sign"></i> Address</th>
                        <th><i class="icon-bookmark"></i> Email</th>
                        <td><span class="label label-info label-mini">Status</span></td>

                        <th></th>

                    </tr>
                </thead>
                <tbody>
                    @foreach (var supplier in Model)
                    {
                        <tr>

                            <td><a href="#">@supplier.CompanyName</a></td>
                            <td class="hidden-phone">@supplier.Address</td>
                            <td>@supplier.Email </td>
                            <td><span class="label label-info label-mini">@supplier.Status</span></td>
                            <td>
                                <button class="btn btn-success btn-xs"><i class="icon-ok"></i></button>
                                <button class="btn btn-primary btn-xs"><i class="icon-pencil">@Html.ActionLink("Update", "UpdateSupplier", new { id = supplier.ID })</i></button>
                                <button class="btn btn-danger btn-xs"><i class="icon-trash "></i>@Html.ActionLink("Delete", "DeleteSupplier", new { id = supplier.ID })</button>
                            </td>

                        </tr>
                    }

                </tbody>
            </table>
        </section>
    </div>
</div>

MVC.UI/Areas/Admin/Views/Supplier/UpdateSupplier.cshtml
@model DAL.Entity.Supplier
@{
    ViewBag.Title = "UpdateSupplier";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<div class="card-body">
    @using (Html.BeginForm("UpdateSupplier", "Supplier", FormMethod.Post))
    {

        <div>
            <label>CompanyName</label>
            @Html.TextBoxFor(x => x.CompanyName, new { @class = "form-control" })

        </div>
        <br />
        <div>
            <label>Address</label>
            @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })

        </div>

        <br />
        <div>
            <label>Email</label>
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })

        </div>

        <button class="btn btn-warning">Update</button>
    }

</div>